### ISSUE TITLE
Error in install requirements.txt

### ISSUE THREAD

**Issue by WooheonHong** [zhhlee/InterFusion#1]
I tried to install requirements, but there is an error.

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0
ERROR: No matching distribution found for tensorflow-gpu==1.12.0
```

My environment is Python: 3.6.6

**Comment by yongmei5** [comment]
Hi hong, I have run into this kind of issue sometimes before. I sort of remembering that I updated the pip with some command like this (depending on your system) "https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl." I referred to it from https://stackoverflow.com/questions/55877398/how-to-install-tensorflow-version-1-12-0-with-pip
