### ISSUE TITLE
conv1d_transpose() got an unexpected keyword argument 'value'

### ISSUE THREAD

**Issue by wzw999** [zhhlee/InterFusion#10]
File "D:\projects\vscode\tensorflow\InterFusion-main\algorithm\conv1d_.py", line 492, in deconv1d
    data_format=data_format
TypeError: conv1d_transpose() got an unexpected keyword argument 'value'

Had anyone come across this kind of issue? Please help me figure it out~

**Comment by ly1112** [comment]
hi, I have the same issue. Have you found a way to solve it? Thanks!
