### ISSUE TITLE
Code problem consultation

### ISSUE THREAD

**Issue by ghost** [zhhlee/InterFusion#12]
Hi, Lee!
     Recently I am reproducing the code of InterFusion， but I got a little bit trouble.
    `import mltk`
     I found that there are many package can be imported like 'mltk', such as 'mltk' and 'pymltookit', but both of them will report errors like'module 'mltk' has no attribute 'Config' '. May you tell me which mltk you installed in InterFusion?Thanks for your help!

**Comment by zhhlee** [comment]
The 'mltk' refers to this repo: https://github.com/haowen-xu/ml-essentials.git, and other requirements are listed in requirements.txt.

**Comment by ghost** [comment]
Thank you very much! So kind of you!
