### ISSUE TITLE
recall and precision

### ISSUE THREAD

**Issue by severous** [zhhlee/InterFusion#13]
The results in the paper only show f1. I would like to know if it is possible to provide recall and precision on the swat dataset and the wadi dataset. Thanks for your reply.

**Comment by zhhlee** [comment]
swat: p: 0.9432, r: 0.9133, f1: 0.9280; wadi: p: 0.96, r: 0.8655, f1: 0.9103.

**Comment by severous** [comment]
Thanks for your reply. I would like to know if it is possible to provide recall and precision on the psm dataset
