### ISSUE TITLE
window_length cannot be set to other values

### ISSUE THREAD

**Issue by JinYang88** [zhhlee/InterFusion#14]
In the class of ModelConfig, when I change the window_length to other values, say, 32, the stack_train.py will throw error.
I vary the window_length several times, it does not work. 

Do you have any idea about this issue? Thanks!

**Comment by zhhlee** [comment]
There are several conv1D & deconv1D layers in the model to derive hidden variable z2. When you change the window_length, the output_shape and z2_dim parameters should be changed accordingly (you may also change the number of conv layers and kernel size, strides if you want). The detailed implementations are in InterFusion.py (or InterFusion_swat.py).
