### ISSUE TITLE
Error in running WADI dataset

### ISSUE THREAD

**Issue by soemthlng** [zhhlee/InterFusion#16]
Hi, I'm trying to run InterFusion with WADI(A2) dataset.

I used these code `python algorithm/stack_train.py --dataset=WADI --train.train_start=259200 --train.max_train_size=789371 --train.valid_portion=0.1 --model.window_length=30 '--model.output_shape=[15, 15, 30]' --model.z2_dim=8 # training` and
`python algorithm/stack_predict.py --load_model_dir=./results/stack_train/ --mcmc_track=False	# evaluation`
When I run `stack_predict.py`, this error occurs 

 # This is my log

*************Evaluate score on testing set************
100%|#############################################################################################################################| 3456/3456 [26:53<00:00,  2.14step/s]

Final testing statistics
==============================================
test_nll                   3940.691162109375
test_lb                    -3965.151123046875
test_recons                -3830.451904296875
test_kl                    134.70001220703125
test_ll                    -3940.691162109375
normal_point_test_recons   -127.42149353027344

*************Evaluate score on training set************

*************Calculating and plotting reconstruction data************
100%|#############################################################################################################################| 3456/3456 [25:54<00:00,  2.39step/s]
(172772, 10, 123)
Traceback (most recent call last):
  File "algorithm/stack_predict.py", line 654, in <module>
    main(exp, exp.config)
  File "algorithm/stack_predict.py", line 549, in main
    train_set_batch_count,
UnboundLocalError: local variable 'train_set_batch_count' referenced before assignment

In stack_predict.py line 481, WADI does not need `train_set_batch_count`. 
Is this problem caused by the WADI dataset's version? or is there any command to run InterFusion with WADI datasets?

**Comment by zhhlee** [comment]
1. You used a different version of WADI dataset, and the data shape maybe different from the configs set in the code.
2. For WADI dataset, when you run stack_predict.py, please add the parameter '--plot_recons_results=False' to skip the 'calculating reconstruction data' procedure on training set (which is very time-consuming).  If you also want to do evaluation on training set, you can change the code in line 481 (stack_predict.py) to do the evaluation.

**Comment by soemthlng** [comment]
Thank you for your reply.

1. Yes, I changed all settings.
2. In stack_predict.py, `--plot_reoncs_results=False` argument works.

**Comment by soemthlng** [comment]
I have a question about WADI dataset's performance.
When I train WADI(A1) and test with `--plot_recons_results=False` argument, performance is very poor.
In your paper section 4.2, the performance of WADI is **0.9103**, but I got **0.3503**.
Are there any arguments to set for good performance? or do I have to change code in `stack_predict.py`?
This is my result.


***  best_f1  ***:  0.35037442778013234
*** threshold ***:  -128.11734

test_nll                   3767.2998046875
test_lb                    -3790.3681640625
test_recons                -3655.095947265625
test_kl                    135.2719268798828
test_ll                    -3767.2998046875
normal_point_test_recons   -121.75577545166016
best-f1                    0.35037442778013234
precision                  0.8385991593505931
recall                     0.22145154782725016
TP                         2203
TN                         162400
FP                         424
FN                         7745
threshold                  -128.11734
auroc                      0.7231228678866259
ap                         0.3112237275344468 Results


**I used the same dataset this time because the last dataset version was unmatched.**

**Comment by zhhlee** [comment]
@soemthlng 1. Please check if you are using the same version of WADI dataset (The folder name is 01_WADI Dataset_09 Oct 2017), and follow the instructions in explib/raw_data_converter.py to prepare the data. (Note that there is a typo in table_WADI.pdf, attack 9. The date should be 11/10/17, follow the time order). 
2. Run the script for WADI listed in the README file.
3. The final test_nll should be about 50000 or higher, it seems that your model was not properly trained (check the data preprocessing and algorithm configurations).

**Comment by soemthlng** [comment]
@zhhlee I followed your instructions.
1. Use WADI A1 dataset and preprocess using `explib/raw_data_converter.py`.
2. Run the script for WADI in README
But, I have a question in 2. I added the argument `--plot_recons_results=False` in `stack_predict.py`.
Is there a reason this argument is not included in `README`?
3. My result was similar to before. There is no differences using `explib/raw_data_converter.py`.
This is my result.

Final testing statistics
=============================================
test_nll                   3749.566162109375
test_lb                    -3770.3876953125
test_recons                -3645.810302734375
test_kl                    124.57722473144531
test_ll                    -3749.566162109375
normal_point_test_recons   -121.3981704711914

*************Evaluate score on training set************

*************Calculating best F1-score*****************
***computing best f1***
***  best_f1  ***:  0.35191366778972266
*** threshold ***:  -127.67305

test_nll                   3749.566162109375
test_lb                    -3770.3876953125
test_recons                -3645.810302734375
test_kl                    124.57722473144531
test_ll                    -3749.566162109375
normal_point_test_recons   -121.3981704711914
best-f1                    0.35191366778972266
precision                  0.8565318784738262
recall                     0.22145154782725016
TP                         2203
TN                         162455
FP                         369
FN                         7745
threshold                  -127.67305
auroc                      0.7302721279454815
ap                         0.3228597290984524 Results

**Comment by zhhlee** [comment]
@soemthlng 1. It's OK to use --plot_recons_results=False for WADI when running stack_predict.py, and I think it won't hurt the performance. I guess the problem is that you do not properly train the base model with stack_train.py.
2. I upload the preprocessed data here: https://1drv.ms/u/s!AsTNHlSUTQHXhAZzBh1CcypQNn3I?e=B8mffx. Please try to retrain the model using this data (as well as the stack_train scripts and parameters for WADI in README).
3. I retrain and evaluate the performance on WADI for several times, and the best-f1 scores are all higher than 0.91 (with GTX2080Ti+tf1.14, or with GTX1080Ti+tf 1.12). To help you reproduce the results, I put one of the trained models and configurations in the above link, which achieves best-f1 around 0.913. You may run stack_predict.py with this model for evaluation.

**Comment by soemthlng** [comment]
@zhhlee 
I tested with your data and your train result, but its performance is still low.
1. I tested with your WADI dataset.  In this case, F1-score is still the same.
This is my result
Final testing statistics
==============================================
test_nll                   3761.08203125
test_lb                    -3785.680908203125
test_recons                -3649.53515625
test_kl                    136.1461181640625
test_ll                    -3761.08203125
normal_point_test_recons   -121.67398071289062

*************Evaluate score on training set************

*************Calculating best F1-score*****************
***computing best f1***
***  best_f1  ***:  0.3525084144827284
*** threshold ***:  -127.91522

test_nll                   3761.08203125
test_lb                    -3785.680908203125
test_recons                -3649.53515625
test_kl                    136.1461181640625
test_ll                    -3761.08203125
normal_point_test_recons   -121.67398071289062
best-f1                    0.3525084144827284
precision                  0.7620768952938649
recall                     0.2292861377997962
TP                         2319
TN                         161934
FP                         724
FN                         7795
threshold                  -127.91522
auroc                      0.733236625590403
ap                         0.30824492175337614 Results

2. I tested with your train result. In this case, F1-score is higher than before, but still very low.
This is my result
Final testing statistics
=============================================
test_nll                   3765.89306640625
test_lb                    -3790.333740234375
test_recons                -3663.179931640625
test_kl                    127.15390014648438
test_ll                    -3765.89306640625
normal_point_test_recons   -121.8533706665039

*************Evaluate score on training set************

*************Calculating best F1-score*****************
***computing best f1***
***  best_f1  ***:  0.3613804832899812
*** threshold ***:  -128.16197

test_nll                   3765.89306640625
test_lb                    -3790.333740234375
test_recons                -3663.179931640625
test_kl                    127.15390014648438
test_ll                    -3765.89306640625
normal_point_test_recons   -121.8533706665039
best-f1                    0.3613804832899812
precision                  0.8525735262773031
recall                     0.2292861377997962
TP                         2319
TN                         162257
FP                         401
FN                         7795
threshold                  -128.16197
auroc                      0.7400281870228925
ap                         0.33175369788452974 Results

My environment setting is as follows: Ubuntu 18.04 LTS Tesla V100-PCIE+tf 1.12

I have no idea why only WADI's result is wired. I will try to find the reason and if I find the reason, I will reopen this issue again.
Thank you for your help.
