### ISSUE TITLE
Can the ASD Dataset Ensure the Absence of Anomalies in the Training Set?

### ISSUE THREAD

**Issue by tangqideng** [zhhlee/InterFusion#18]
There is a concern regarding whether the ASD dataset can guarantee the absence of anomalies in the training set.

**Comment by zhhlee** [comment]
No, there might be a small number of anomalies in the training set of ASD, although most of the training data are normal. For the four datasets used in paper, SWaT and WADI only contain normal data in their training set.

**Comment by tangqideng** [comment]
Thanks!
