### ISSUE TITLE
hello,which mltk version do you use?

### ISSUE THREAD

**Issue by LiLanNaYang** [zhhlee/InterFusion#5]
AttributeError: module 'mltk' has no attribute 'Config'

**Comment by zhhlee** [comment]
@LiLanNaYang  mltk is in package ML-Essentials (version 0.0.2, the latest version). You can install it via 'pip install git+https://github.com/haowen-xu/ml-essentials.git'.

**Comment by LiLanNaYang** [comment]
It's ok, thank you very much.
