### ISSUE TITLE
Can not install the requirements

### ISSUE THREAD

**Issue by Ian-Jhon** [zhhlee/InterFusion#6]
When I ran `pip3 install -r requirements.txt`, a warning rised.

```
Collecting git+https://github.com/thu-ml/zhusuan.git@48c0f4e (from -r requirements.txt (line 17))
  Cloning https://github.com/thu-ml/zhusuan.git (to revision 48c0f4e) to /tmp/pip-req-build-fg_b1f04
  Running command git clone --filter=blob:none -q https://github.com/thu-ml/zhusuan.git /tmp/pip-req-build-fg_b1f04
  WARNING: Did not find branch or tag '48c0f4e', assuming revision or ref.
```

**Comment by zhhlee** [comment]
It's an intermediate version of zhusuan. You can manually install it via pip install, or directly install the tfsnippet 0.2.0a4 as in requirements (installing tfsnippet via pip will automatically install the correct version of zhusuan).
