### ISSUE TITLE
【ValueError】high is out of bounds for int32

### ISSUE THREAD

**Issue by 04756** [zhhlee/InterFusion#9]
I have install the modules requested according the requested.txt and the project runs on the Windows OS. But i meet this issue when I run "python algorithm/stack_train.py --dataset=omi-1".
At first, it shows in the line 143-145 of stack_train.py.
![image](https://user-images.githubusercontent.com/31569881/153025980-b6478f33-3992-4ce9-a615-fd123eff5b24.png)
Then i change "0xffffffff" to "(1 << 31) - 1)" and fix the error which happened here. However, it still happens in another file.
![image](https://user-images.githubusercontent.com/31569881/153025754-3e5e0b86-4c67-459a-89ba-01e758d1c502.png)

**Comment by 04756** [comment]
The issue would not happens when the project runs on the ubuntu OS.

**Comment by wzw999** [comment]
add a parameter dtype=int64

**Comment by 04756** [comment]
Thanks！It works！



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 29, 2022 09:57 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zhhlee/InterFusion] 【ValueError】high is out of bounds for int32 (Issue #9)




 
add a parameter dtype=int64
